server:
  port: 8001
  servlet.context-path: /mgt
      
logging:
  file: logs/vp-mgt.log #can use relative position for the log configuration
  level:
    root: info
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
pc.upload.path: /upload/pc_pic
pc.rest.url: http://localhost:8002/rest-api
pc.admin.url: /admin/pc



auth.core.base.url: http://localhost:8003
auth.core.context-path: /auth-api